version: "3"
services:
  npm:
    image: node:8-alpine
    entrypoint: ["npm"]
    command: ["install"]
    working_dir: /app
    volumes:
        - ./:/app
  migrate:
    image: node:8-alpine
    command: ["npm", "run", "sequelize", "db:migrate"]
    working_dir: /app
    volumes:
        - ./:/app
    depends_on:
      - npm
      - db
  db:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movietone
      MYSQL_USER: movietone
      MYSQL_PASSWORD: movietone
    ports:
      - "3306:3306"
