version: "3"
services:
  npm:
    image: node:8-alpine
    entrypoint: ["npm"]
    command: ["install"]
    working_dir: /app
    volumes:
        - ./:/app
  db:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movietone
      MYSQL_USER: movietone
      MYSQL_PASSWORD: movietone
    volumes:
      - ./api/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
