version: "3"
services:
  npm:
    image: node:10-alpine
    entrypoint: ["npm"]
    command: ["install"]
    working_dir: /app
    volumes:
        - ./:/app
  api:
    image: node:10-alpine
    entrypoint: ["npm"]
    command: ["run", "api:tsc-watch"]
    working_dir: /app
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    depends_on:
      - npm
      - db
  db:
    image: mysql:5
    env_file: .env
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
        - "3306:3306"
    volumes:
      - "./api/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro"