enum TypeKeys {
    GET_MOVIES         = 'GET_MOVIES',
    SET_MOVIES         = 'SET_MOVIES',
    SET_ACTIVE_MOVIE   = 'SET_ACTIVE_MOVIE',
    GET_MOVIE          = 'GET_MOVIE',
    DELETE_MOVIE       = 'DELETE_MOVIE',
    SET_EDITING_FIELD  = 'SET_EDITING_FIELD',
    CLEAR_EDITING      = 'CLEAR_EDITING',
    SET_CREATING_FIELD = 'SET_CREATING_FIELD',
    CLEAR_CREATING     = 'CLEAR_CREATING',
    SAVE_MOVIE         = 'SAVE_MOVIE',
    ADD_FILTER         = 'ADD_FILTER',
    DELETE_FILTER      = 'DELETE_FILTER'
}

export default TypeKeys;