enum TypeKeys {
    GET_MOVIES       = 'GET_MOVIES',
    SET_MOVIES       = 'SET_MOVIES',
    SET_ACTIVE_MOVIE = 'SET_ACTIVE_MOVIE',
    GET_MOVIE    = 'GET_MOVIE',
    CREATE_MOVIE = 'CREATE_MOVIE',
    UPDATE_MOVIE = 'UPDATE_MOVIE',
    DELETE_MOVIE = 'DELETE_MOVIE',
}

export default TypeKeys;